version: 2
jobs:
  build:
    docker: #  tircleci/node:10.0.0 # the primary container, where your job's commands are run
        - image: circleci/node:7.10  # run in the background
        
    working_directory: ~/repo
    
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - v1-dependencies-{( checksum 'package.json' )}
            # fallback to use internet cache if no exact match is found
            - v1-dependencies-
 
 - run: yarm install

  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{( checksum 'package.json' )}
      
  # run tests!
  - run: yarm test
